theme: jekyll-theme-slate
title: Maths Club
description: EARLY ALPHA
markdown: kramdown

collections:
  posts:
    output: true
    permalink: /posts/:title
    
plugins:
  - jekyll-feed
  
kramdown:
    math_engine: katex
feed:
  posts_limit: 20
  excerpt_only: true
